### ISSUE TITLE
Reminders Permission

### ISSUE THREAD

**Issue by jlaws** [danielebogo/DBPrivacyHelper#12]

**Comment by jlaws** [comment]
I integrated DBPrivacyHelper into JLPermissions - https://github.com/jlaws/JLPermissions - and for consistency it would be great if you added support for reminders permissions.

**Comment by danielebogo** [comment]
Thanks @jlaws , it's done! [tag 0.6](https://github.com/danielebogo/DBPrivacyHelper/tree/0.6)
