### ISSUE TITLE
Push notifications?

### ISSUE THREAD

**Issue by RomainBoulay** [danielebogo/DBPrivacyHelper#3]
Hey,

That would be awesome to have a push notification version (DBPrivacyTypePush ?)

Is that planned?

Thanks,
Romain

**Comment by dagobert-duck** [comment]
+1

**Comment by danielebogo** [comment]
I'm working on it. Try the last commit on master. I need to implement other cases before tag a new version. Thanks guys for us it!

**Comment by RomainBoulay** [comment]
Thanks! Will take a look ;)
